### ISSUE TITLE
docker-compose: OpenVPN working, NordLynx not

### ISSUE THREAD

**Issue by klara31** [bubuntux/nordvpn#75] opened 2020-05-10 14:15 UTC
### Before submitting review [Troubleshooting](https://github.com/bubuntux/nordvpn/wiki/Troubleshooting) and open/closed [Issues](https://github.com/bubuntux/nordvpn/issues?q=) ###

**Describe the bug**
I have the following docker-compose.yml file:
```
  vpn:
    image: bubuntux/nordvpn:latest
    container_name: vpn
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    ports:
      - 8112:8112 # Deluge
      - 6789:6789 # nzbget
    environment:
      - USER=xxx@xxx.xx
      - PASS=123456789
      - CONNECT=Netherlands
      - TECHNOLOGY=OpenVPN
      - TZ=${TZ}
      - NETWORK=192.168.10.0/24
```
When I change ```TECHNOLOGY=NordLynx```, the containers using this VPN service do not connect anymore to the internet. Docker container health status remains at ```Starting```. Log says ```connected```.  CPU is at 100%. The containers using the VPN service are NZBget and Deluge. I can't figure out what's going wrong.

**Logs**
Add DEBUG=on and copy the logs here (make sure to remove you user and password from the logs as well).
```
+ [[ -n '' ]]
+ [[ '' =~ ^[0-9]+$ ]]
++ ip -o addr show dev eth0
++ awk '$3 == "inet" {print $4}'
+ DOCKER_NET=172.17.0.5/16
+ kill_switch
++ ip -o addr show dev eth0
++ awk '$3 == "inet6" {print $4; exit}'
+ local docker6_network=
+ iptables -F
+ iptables -X
+ iptables -P INPUT DROP
+ iptables -P FORWARD DROP
+ iptables -P OUTPUT DROP
+ iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A INPUT -i lo -j ACCEPT
+ iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A FORWARD -i lo -j ACCEPT
+ iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ iptables -A OUTPUT -o lo -j ACCEPT
+ iptables -A OUTPUT -o tap+ -j ACCEPT
+ iptables -A OUTPUT -o tun+ -j ACCEPT
+ iptables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ iptables -t nat -A POSTROUTING -o tap+ -j MASQUERADE
+ iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE
+ [[ -n 172.17.0.5/16 ]]
+ iptables -A INPUT -s 172.17.0.5/16 -j ACCEPT
+ iptables -A FORWARD -d 172.17.0.5/16 -j ACCEPT
+ iptables -A FORWARD -s 172.17.0.5/16 -j ACCEPT
+ iptables -A OUTPUT -d 172.17.0.5/16 -j ACCEPT
+ [[ -n 192.168.10.0/24 ]]
+ for net in ${NETWORK//[;,]/ }
+ return_route 192.168.10.0/24
++ ip route
++ awk '/default/ {print $3}'
+ local network=192.168.10.0/24 gw=172.17.0.1
+ grep -q 192.168.10.0/24
+ ip route
+ ip route add to 192.168.10.0/24 via 172.17.0.1 dev eth0
+ iptables -A INPUT -s 192.168.10.0/24 -j ACCEPT
+ iptables -A FORWARD -d 192.168.10.0/24 -j ACCEPT
+ iptables -A FORWARD -s 192.168.10.0/24 -j ACCEPT
+ iptables -A OUTPUT -d 192.168.10.0/24 -j ACCEPT
+ [[ -n '' ]]
+ ip6tables -F
+ ip6tables -X
+ ip6tables -P INPUT DROP
+ ip6tables -P FORWARD DROP
+ ip6tables -P OUTPUT DROP
+ ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A INPUT -p icmp -j ACCEPT
+ ip6tables -A INPUT -i lo -j ACCEPT
+ ip6tables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A FORWARD -p icmp -j ACCEPT
+ ip6tables -A FORWARD -i lo -j ACCEPT
+ ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+ ip6tables -A OUTPUT -o lo -j ACCEPT
+ ip6tables -A OUTPUT -o tap+ -j ACCEPT
+ ip6tables -A OUTPUT -o tun+ -j ACCEPT
+ ip6tables -A OUTPUT -m owner --gid-owner vpn -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT
+ ip6tables -A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT
+ ip6tables -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
+ ip6tables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
+ ip6tables -A OUTPUT -o eth0 -d api.nordvpn.com -j ACCEPT
+ [[ -n '' ]]
+ [[ -n '' ]]
+ pkill nordvpnd
+ rm -f /run/nordvpnd.sock
+ sleep 0.5
+ sg vpn -c nordvpnd
+ nordvpn login -u xxxx@xxx.xx -p '12345678'
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
+ setup_nordvpn
+ [[ -n NordLynx ]]
+ nordvpn set technology NordLynx
Technology is successfully set to 'NordLynx'.
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n 172.17.0.5/16 ]]
+ nordvpn whitelist add subnet 172.17.0.5/16
Subnet 172.17.0.0/16 is whitelisted successfully.
+ [[ -n 192.168.10.0/24 ]]
+ for net in ${NETWORK//[;,]/ }
+ nordvpn whitelist add subnet 192.168.10.0/24
Subnet 192.168.10.0/24 is whitelisted successfully.
+ [[ -n on ]]
+ nordvpn -version
NordVPN Version 3.7.2
+ nordvpn settings
Technology: NordLynx
Kill Switch: disabled
CyberSec: disabled
Notify: disabled
Auto-connect: disabled
DNS: disabled
Whitelisted subnets:
        172.17.0.0/16
        192.168.10.0/24
+ create_tun_device
+ mkdir -p /dev/net
+ [[ -c /dev/net/tun ]]
+ nordvpn connect Netherlands
-2020/05/10 16:07:44 PRE_CONNECT system info:
App Version: 3.7.2
OS Info:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

System Info:Linux 08ffc59382bd 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 GNU/Linux


Routing Table:
default via 172.17.0.1 dev eth0
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.5
192.168.10.0/24 via 172.17.0.1 dev eth0

IP Rules:
0:      from all lookup local
32766:  from all lookup main
32767:  from all lookup default

IP Tables:
filter:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 172.17.0.0/16 -j ACCEPT
-A INPUT -s 192.168.10.0/24 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.0/16 -j ACCEPT
-A FORWARD -s 172.17.0.0/16 -j ACCEPT
-A FORWARD -d 192.168.10.0/24 -j ACCEPT
-A FORWARD -s 192.168.10.0/24 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap+ -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -m owner --gid-owner 104 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -j ACCEPT
-A OUTPUT -d 192.168.10.0/24 -j ACCEPT

nat:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -o tap+ -j MASQUERADE
-A POSTROUTING -o tun+ -j MASQUERADE

mangle:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT

raw:
-P PREROUTING ACCEPT
-P OUTPUT ACCEPT

security:
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

IP Set:


Connecting to Netherlands #600 (nl600.nordvpn.com)
\INFO: (nordlynx) 2020/05/10 16:07:47 Attaching to interface
INFO: (nordlynx) 2020/05/10 16:07:47 Interface set up
INFO: (nordlynx) 2020/05/10 16:07:47 Device started
2020/05/10 16:07:47 address :10.5.0.2/16
2020/05/10 16:07:47 [nordlynx] ip -4 address add 10.5.0.2/16 dev nordlynx
2020/05/10 16:07:47 [nordlynx] ip link set mtu 1420 up dev nordlynx
|2020/05/10 16:07:47 sysctl: setting key "net.ipv6.conf.all.disable_ipv6": Read-only file system
We could not disable IPv6. For more information, please check activity log.
-2020/05/10 16:07:47 [Warning] route(s) for whitelisted subnet(s) via non-default gateway already exist in the system
2020/05/10 16:07:47 BACKUP:
 *filter
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.0/16 -j ACCEPT
-A FORWARD -s 172.17.0.0/16 -j ACCEPT
-A FORWARD -d 192.168.10.0/24 -j ACCEPT
-A FORWARD -s 192.168.10.0/24 -j ACCEPT
-P INPUT DROP
-P OUTPUT DROP
-A OUTPUT -p udp -d 103.86.96.100 --dport 53 -o lo -j ACCEPT
-A OUTPUT -p udp -d 103.86.99.100 --dport 53 -o lo -j ACCEPT
-A OUTPUT -p udp -d 103.86.96.100 --dport 53 -o nordlynx -j ACCEPT
-A OUTPUT -p udp -d 103.86.99.100 --dport 53 -o nordlynx -j ACCEPT
-A OUTPUT -o nordlynx -p all -d 0.0.0.0/0 -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -i nordlynx -j ACCEPT
-A OUTPUT -o lo -d 178.239.173.195 -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -i lo -s 178.239.173.195 -j ACCEPT
-A OUTPUT -o lo -d 127.0.0.1/8 -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -i lo -s 127.0.0.1/8 -j ACCEPT
-A OUTPUT -o nordlynx -d 178.239.173.195 -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -i nordlynx -s 178.239.173.195 -j ACCEPT
-A OUTPUT -o nordlynx -d 10.5.0.2/16 -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -i nordlynx -s 10.5.0.2/16 -j ACCEPT
-A OUTPUT -o eth0 -d 178.239.173.195 -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -i eth0 -s 178.239.173.195 -j ACCEPT
-A OUTPUT -o eth0 -d 172.17.0.5/16 -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -i eth0 -s 172.17.0.5/16 -j ACCEPT
-A INPUT -p udp --dport 51820:51820 -i lo -s 127.0.0.1/8 -j ACCEPT
-A INPUT -i lo -m conntrack --ctstate NEW,ESTABLISHED,RELATED -s 172.17.0.0/16 -j ACCEPT
-A OUTPUT -o lo -d 172.17.0.0/16 -j ACCEPT
-A INPUT -i lo -m conntrack --ctstate NEW,ESTABLISHED,RELATED -s 192.168.10.0/24 -j ACCEPT
-A OUTPUT -o lo -d 192.168.10.0/24 -j ACCEPT
-A INPUT -p udp --dport 51820:51820 -i eth0 -s 172.17.0.5/16 -j ACCEPT
-A INPUT -i eth0 -m conntrack --ctstate NEW,ESTABLISHED,RELATED -s 172.17.0.0/16 -j ACCEPT
-A OUTPUT -o eth0 -d 172.17.0.0/16 -j ACCEPT
-A INPUT -i eth0 -m conntrack --ctstate NEW,ESTABLISHED,RELATED -s 192.168.10.0/24 -j ACCEPT
-A OUTPUT -o eth0 -d 192.168.10.0/24 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
COMMIT

2020/05/10 16:07:47 [nordlynx] ip -4 route add 0.0.0.0/0 dev nordlynx table 51820
2020/05/10 16:07:47 [nordlynx] ip -4 rule add to 178.239.173.195 lookup main priority 32765
2020/05/10 16:07:47 [nordlynx] ip -4 rule add not fwmark 51820 table 51820 priority 32764
2020/05/10 16:07:47 [nordlynx] ip -4 rule add table main suppress_prefixlength 0 priority 32763
You are connected to Netherlands #600 (nl600.nordvpn.com)!
-2020/05/10 16:07:47 POST_CONNECT system info:
Routing Table:
default via 172.17.0.1 dev eth0
10.5.0.0/16 dev nordlynx proto kernel scope link src 10.5.0.2
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.5
192.168.10.0/24 via 172.17.0.1 dev eth0

IP Rules:
0:      from all lookup local
32763:  from all lookup main suppress_prefixlength 0
32764:  not from all fwmark 0xca6c lookup 51820
32765:  from all to 178.239.173.195 lookup main
32766:  from all lookup main
32767:  from all lookup default

IP Tables:
filter:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -i nordlynx -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 178.239.173.195/32 -i lo -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 127.0.0.0/8 -i lo -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 178.239.173.195/32 -i nordlynx -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 10.5.0.0/16 -i nordlynx -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 178.239.173.195/32 -i eth0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 172.17.0.0/16 -i eth0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 127.0.0.0/8 -i lo -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -s 172.17.0.0/16 -i lo -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 192.168.10.0/24 -i lo -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 172.17.0.0/16 -i eth0 -p udp -m udp --dport 51820 -j ACCEPT
-A INPUT -s 172.17.0.0/16 -i eth0 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT
-A INPUT -s 192.168.10.0/24 -i eth0 -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 172.17.0.0/16 -j ACCEPT
-A FORWARD -s 172.17.0.0/16 -j ACCEPT
-A FORWARD -d 192.168.10.0/24 -j ACCEPT
-A FORWARD -s 192.168.10.0/24 -j ACCEPT
-A OUTPUT -d 103.86.96.100/32 -o lo -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -d 103.86.99.100/32 -o lo -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -d 103.86.96.100/32 -o nordlynx -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -d 103.86.99.100/32 -o nordlynx -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -o nordlynx -j ACCEPT
-A OUTPUT -d 178.239.173.195/32 -o lo -j ACCEPT
-A OUTPUT -d 127.0.0.0/8 -o lo -j ACCEPT
-A OUTPUT -d 178.239.173.195/32 -o nordlynx -j ACCEPT
-A OUTPUT -d 10.5.0.0/16 -o nordlynx -j ACCEPT
-A OUTPUT -d 178.239.173.195/32 -o eth0 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -o eth0 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -o lo -j ACCEPT
-A OUTPUT -d 192.168.10.0/24 -o lo -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -o eth0 -j ACCEPT
-A OUTPUT -d 192.168.10.0/24 -o eth0 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT

nat:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -o tap+ -j MASQUERADE
-A POSTROUTING -o tun+ -j MASQUERADE

mangle:
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT

raw:
-P PREROUTING ACCEPT
-P OUTPUT ACCEPT

security:
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

IP Set:


+ nordvpn status
Status: Connected
Current server: nl600.nordvpn.com
Country: Netherlands
City: Amsterdam
Your new IP: 178.239.173.215
Current technology: NordLynx
Uptime: 0 seconds
++ pidof nordvpnd
+ tail -f --pid=112 /var/log/nordvpn/daemon.log
-P OUTPUT ACCEPT

security:
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT

IP Set:

```
**Additional context**
Running on Ubuntu 18.04LTS on a x86_64

**Comment by bubuntux** [comment] 2020-05-10 23:51
everything looks fine on the logs, are you restarting all the containers attached to the network?
try taking everything down
`docker-compose down`
then bring everything back up
`docker-compose up -d`

**Comment by frdmn** [comment] 2020-05-11 06:22
I have exactly the same issue and haven't found a solution yet to this. Tried the dev branch, adding all the capabilities, different countries - nothing worked so far.

**Comment by klara31** [comment] 2020-05-11 12:22
@bubuntux tried that, same result...

**Comment by bubuntux** [comment] 2020-05-11 15:42
seems like the vpn container is working fine, are you able to 
`docker exec -ti vpncontainer bash` and run `curl https://api.nordvpn.com/vpn/check/full ` you should see the connection is protected.
if that works fine, then attach to one of the other containers using the same network and try the same, maybe is just the routing of the containers that is not working

**Comment by GabrielSturtevant** [comment] 2020-05-11 23:49
I am having the exact same issue.

Logs from the container startup shows I am successfully connected to NordVPN using NordLynx. It shows my new IP, but when I go into the container shell and try to run `curl icanhazip.com` it just hangs. Pinging `8.8.8.8` also hangs.

**Comment by bubuntux** [comment] 2020-05-12 04:39
@GabrielSturtevant any error on the logs? timeout, etc , try
`sg vpn -c "ping 8.8.8.8" `
`sg vpn -c "curl icanhazip.com"`
seems like the dns is not resolving, you could also try adding dns manually through the env variable DNS.

**Comment by klara31** [comment] 2020-05-12 09:36
When you ping an IP address directly, DNS is not used...

**Comment by frdmn** [comment] 2020-05-13 07:14
@bubuntux No success with the `sg vpn -c "..."` commands either: 

```
root@dell-r220:/opt/docker/nordvpn# docker-compose exec vpn bash
root@bd5a9a047235:/# sg vpn -c "ping 8.8.8.8"
PING 8.8.8.8 (8.8.8.8): 56 data bytes
^C--- 8.8.8.8 ping statistics ---
217 packets transmitted, 0 packets received, 100% packet loss
root@bd5a9a047235:/# sg vpn -c "curl icanhazip.com"
curl: (6) Could not resolve host: icanhazip.com
root@bd5a9a047235:/# curl icanhazip.com
curl: (6) Could not resolve host: icanhazip.com
root@bd5a9a047235:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sending packet: Operation not permitted
```

The only errors I see in the logs are these: 

```
nordvpn | 2020/05/13 07:10:26 Get "https://zwyr157wwiu6eior.com/v1/servers/recommendations?limit=2&filters[servers.status]=online&filters[servers_technologies]=35&filters[servers_technologies][pivot][status]=online&fields[servers.id]&fields[servers.name]&fields[servers.hostname]&fields[servers.station]&fields[servers.load]&fields[servers.created_at]&fields[servers.groups.id]&fields[servers.groups.title]&fields[servers.technologies.id]&fields[servers.technologies.pivot.status]&fields[servers.specifications.identifier]&fields[servers.specifications.values.value]&fields[servers.locations.country.name]&fields[servers.locations.country.code]&fields[servers.locations.country.city.name]&fields[servers.locations.country.city.latitude]&fields[servers.locations.country.city.longitude]&coordinates[longitude]=9.930800&coordinates[latitude]=49.778600&filters[country_id]=228": dial tcp: i/o timeout
nordvpn | 2020/05/13 07:10:26 Get "https://zwyr157wwiu6eior.com/v1/servers/recommendations?limit=2&filters[servers.status]=online&filters[servers_technologies]=35&filters[servers_technologies][pivot][status]=online&fields[servers.id]&fields[servers.name]&fields[servers.hostname]&fields[servers.station]&fields[servers.load]&fields[servers.created_at]&fields[servers.groups.id]&fields[servers.groups.title]&fields[servers.technologies.id]&fields[servers.technologies.pivot.status]&fields[servers.specifications.identifier]&fields[servers.specifications.values.value]&fields[servers.locations.country.name]&fields[servers.locations.country.code]&fields[servers.locations.country.city.name]&fields[servers.locations.country.city.latitude]&fields[servers.locations.country.city.longitude]&coordinates[longitude]=9.930800&coordinates[latitude]=49.778600&filters[country_id]=228": dial tcp: i/o timeout
nordvpn | 2020/05/13 07:10:56 [Error] ntp check failed
nordvpn | INFO: (nordlynx) 2020/05/13 07:10:56 Device closing
nordvpn | INFO: (nordlynx) 2020/05/13 07:10:56 Interface closed
```

([full log output](https://paste.frd.mn/ipuneqeyur))

As @klara31 mentioned, it doesn't seem to be related to DNS since any of the outbound connections fail no matter the IP protocol. TCP, UDP and ICMP all seem to fail.

**Comment by hemna** [comment] 2020-05-13 13:45
I'm having the same problem.  the container is stuck in 'starting' state.   It says the vpn is up, but when I ping from inside the container, I get nothing.  It looks like a DNS issue for me.

```
+ nordvpn status|
Status: Connected
nordvpn         | Current server: us5342.nordvpn.com
nordvpn         | Country: United States
nordvpn         | City: Manassas
nordvpn         | Your new IP: 162.210.198.129
nordvpn         | Current technology: NordLynx
nordvpn         | Transfer: 0 B received, 152 B sent
nordvpn         | Uptime: 0 seconds
nordvpn         | ++ pidof nordvpnd
nordvpn         | + tail -f --pid=71 /var/log/nordvpn/daemon.log
nordvpn         | -P OUTPUT ACCEPT
nordvpn         |
nordvpn         | security:
nordvpn         | -P INPUT ACCEPT
nordvpn         | -P FORWARD ACCEPT
nordvpn         | -P OUTPUT ACCEPT
nordvpn         |
nordvpn         | IP Set:
nordvpn         |
nordvpn         |
```

From inside the container

````
root@21eb548d47b4:/# cat /etc/resolv.conf
# Generated by NordVPN
nameserver 103.86.99.99
nameserver 103.86.96.96root@21eb548d47b4:/# ping 103.86.99.99
PING 103.86.99.99 (103.86.99.99): 56 data bytes
^C--- 103.86.99.99 ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
root@21eb548d47b4:/# ping 103.86.99.96
PING 103.86.99.96 (103.86.99.96): 56 data bytes
^C--- 103.86.99.96 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
root@21eb548d47b4:/# ping cnn.com
ping: unknown host
```

**Comment by toddnotplaying** [comment] 2020-05-16 17:09
I've been struggling with this issue which I've traced to the following:

This container won't resolve DNS if it's attempted to run on ANY network except the default bridge network. Even running it in a user-generated bridge network causes it to fail.

My workaround (which I dislike) is to attach all the services to the default bridge network and use the legacy --link option to workaround the limitations of the default bridge network.

I had been debugging with NordLynx but in my testing switched back to OpenVPN and it appears that this issue of not running on user generated bridge networks isn't related to that specifically.

The results are the same, if you run this container in any network OTHER than the default bridge network, it will fail. 

resolve.conf when connected to the DEFAULT BRIDGE:

`root@27a45391cae7:/# cat /etc/resolv.conf
# Generated by NordVPN
nameserver 103.86.96.100`

resolve.conf when connected to a user-defined bridge network"

`root@d962c902eb47:/# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0`

all other services attached to that same user-defined bridge network have no problems resolving DNS

**Comment by ABredhauer** [comment] 2020-05-22 08:30
This seems to be more of a routing issue than a DNS issue.
Output of ip route when using NordLynx

```
root@7016ca895c9a:/# ip route
default via 172.17.0.1 dev eth0 
10.5.0.0/16 dev nordlynx proto kernel scope link src 10.5.0.2 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2 
192.168.65.0/24 via 172.17.0.1 dev eth0 
```

Output when using OpenVPN
```
root@5095baae0686:/# ip route
0.0.0.0/1 via 10.8.3.1 dev tun0 
default via 172.17.0.1 dev eth0 
10.8.3.0/24 dev tun0 proto kernel scope link src 10.8.3.19 
45.248.77.157 via 172.17.0.1 dev eth0 
128.0.0.0/1 via 10.8.3.1 dev tun0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2 
192.168.65.0/24 via 172.17.0.1 dev eth0 
```

**Comment by frdmn** [comment] 2020-05-22 16:24
I agree with @ABredhauer - as I already mentioned in a comment earlier, no IP traffic is sent no matter the protocol (TCP / UDP / ICMP, ...). Definitely not a DNS issue.

**Comment by micbase** [comment] 2020-05-22 20:32
I think the routing table is set correctly
```
root@3bd4cc091dc3:/# ip route show table 51820
default dev nordlynx scope link
```

```
root@3bd4cc091dc3:/# ip rule
0:	from all lookup local
32763:	from all lookup main suppress_prefixlength 0
32764:	not from all fwmark 0xca6c lookup 51820
32765:	from all to 84.17.53.158 lookup main
32766:	from all lookup main
32767:	from all lookup default
```

It seems nordvpn is using the technic from wireguard official guide https://www.wireguard.com/netns/ the "Improved Rule-based Routing" section. Basically what it does is: if the IP matches the main routing table with the default route, it will not go to that route, ip rule rejects the rule(32763) and go to the next rule(32764), which use the 51820 routing table, in which the default route is nordvpn.


I found that if you run
```
ip rule add from all to 84.17.53.158 lookup main
```
or
```
ip route add 84.17.53.158 via 172.17.0.1 dev eth0
```

that can fix the internet access.

But I'm still confused why the 32764 rule didn't work for the connection to nordvpn server(84.17.53.158 in this case). I assume nordvpn sets the fwmark to 51820(0xca6c), so encrypted UDP traffic go out of nordlynx interface should have the fwmark set to 51820, and rule 32764 should not match, and go to next rule. Rule 32765 is redundant IMO.

**Comment by aureleoules** [comment] 2020-05-25 02:43
> ip rule add from all to [public ip] lookup main

This fixed it for me, but that's not clean

**Comment by aureleoules** [comment] 2020-05-25 14:51
It is not only a docker-compose problem, NordLynx doesn't work with a simple docker run either.
Though, it works on a 4.19.84-microsoft-standard kernel on Windows (WSL 2).

**Comment by micbase** [comment] 2020-05-25 17:34
Found an elegant solution, add this to your docker run parameter or docker compose:
```
--sysctl net.ipv4.conf.all.rp_filter=2
```
You can also only apply this to your eth0 interface(the one sends encrypted packets to nordvpn server)
```
--sysctl net.ipv4.conf.eth0.rp_filter=2
```

**Comment by wvzuilen** [comment] 2020-05-25 20:27
I'm having the same issue and I can confirm @micbase 's workaround (?) works.

**Comment by frdmn** [comment] 2020-05-26 12:24
I can confirm this as well. I'm using the following docker-compose configuration:

```
version: "3"
services:
  nordvpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - net_admin
      - sys_module
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.conf.eth0.rp_filter=2
    environment:
      - ...
```

Thanks @micbase!

**Comment by bubuntux** [comment] 2020-05-27 03:33
@micbase  thanks!

still unclear to me why it doesn't work for you guys unless you add that setting tbh.
i'm gonna add it on the wiki troubleshooting for now, 
can someone please create a pull request to add this information into the README ?

**Comment by bubuntux** [comment] 2020-05-31 04:17
I just pushed a few changes into the dev branch, that may fix this issues and also remove the need for NETWORK env variables. 

can someone give it a try and report back ?

**Comment by alpha017** [comment] 2020-05-31 09:27
@bubuntux , it doesn't work for me.
But in my case, it doesn't work either with the previous fix (OpenVpn works well).

Tested with firefox and qbittorent.

I noticed with qbittorent that the connection works for a few seconds after the launch of the vpn and then stop.

**Comment by fishtenors** [comment] 2020-06-01 18:38
I was able to get this working with the following compose config:

`
services:
  vpn:
    image: bubuntux/nordvpn:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    environment:
      USER: <username>
      PASS: <password>
      CONNECT: United_States
      TECHNOLOGY: NordLynx
      TZ: America/Los_Angeles
      GROUPID: 0
    ports:
      - "9091:9091"
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
`
Going to do some more testing to confirm, but I think with the SYS_ADMIN capability, I had to set the GROUPID to 0, and SYS_ADMIN is necessary for NordLynx to work, right?

Also, big ups to @micbase `net.ipv4.conf.all.rp_filter` was the difference maker on the routing issue.

**Closed** 2020-06-01 23:03 UTC
Labels: bug, help wanted

**Comment by adit-s** [comment] 2020-06-13 19:24
Hello. I just pulled this container for the first time today, Jun 13, and ran into the same issue using NordLynx. Everything else works perfectly. 
I see the issue is closed, but I ran into the same problem and wasn't able to get it working. Perhaps it's in the earlier comments and I missed it but what was the resolution?
(using @micbase suggestion didn't work for me)

Thanks,
A Sood

**Comment by fishtenors** [comment] 2020-06-14 15:31
@adit-s See my comment above. Note the SYS_ADMIN capability, GROUPID and sysctls settings. Have you tried running it with those exact settings in your environment?

**Comment by Dimitvp** [comment] 2020-11-03 06:44
I am not sure that I have to open a new issue for me questions so I`ll ask them here:

1. How reliable is this VPN used in Docker? 
We are using it directly on the server and its doing fine. Now we want to use it in a Docker but I am trying to set it up for two weeks (following everything written in the issues in this repo) And I notice that some times it connects to the NordVPN`s servers for seconds, sometimes it doesn`t connect at all.

2. Is it possible to have 2,3,4 etc. Docker containers on the same server, connected to different countries?

**Comment by dvcrn** [comment] 2022-10-24 06:41
Hi everyone, this is from 2020 but I still ran into the same issue. Had to add `net.ipv4.conf.all.rp_filter=2` and now all is good again
