### ISSUE TITLE
Real IP was used by containers

### ISSUE THREAD

**Issue by ctscobra** [bubuntux/nordvpn#173] opened 2021-05-10 14:20 UTC
### Before submitting review [Troubleshooting](https://github.com/bubuntux/nordvpn/wiki/Troubleshooting) and open/closed [Issues](https://github.com/bubuntux/nordvpn/issues?q=) ###

**Describe the bug**
All was working fine for few days then i noticed that other containers started using real-IP with "curl ifconfig.me" , on nordvpn container i seen status as connected but update available . Did a docker-compose pull and start and all is fine again but why did my IP bleed to the containers , especially to torrent download.

`root@d51eb0df8a26:/# nordvpn status
A new version of NordVPN is available! Please update the application.
Status: Connected
Current server: de874.nordvpn.com
Country: Germany
City: Frankfurt
Your new IP: 185.220.70.215
Current technology: OpenVPN
Current protocol: TCP
Transfer: 6.43 GiB received, 289.81 MiB sent
Uptime: 12 hours 50 minutes 8 seconds`

Docker-compose:
`---
version: "3"
services:
  nordvpn:
    image: bubuntux/nordvpn:latest
    container_name: nordvpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=*********
      - PASS=**********
      - COUNTRY=Croatia
      - PROTOCOL=TCP
      - CATEGORY=P2P
      - NETWORK=192.168.0.0/16
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=Europe/Berlin
    ports:
      - 9091:9091
      - 51413:51413
      - 9117:9117
      - 8989:8989
      - 8686:8686
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=******* #optional
      - PASS=************* #optional
      - WHITELIST=192.168.*.* 127.0.0.1 #optional
      - HOST_WHITELIST=dnsnane list #optional
    volumes:
      -**************
    restart: unless-stopped
    network_mode: service:nordvpn
    depends_on:
      - nordvpn
      
      
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ***********
    restart: unless-stopped
    network_mode: service:nordvpn
    depends_on:
      - nordvpn

  lidarr:
    image: linuxserver/lidarr:nightly
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - *********
    restart: unless-stopped
    network_mode: service:nordvpn
    depends_on:
      - nordvpn`

**Comment by bubuntux** [comment] 2021-05-17 03:51
you mind giving it a try again, i added a change in the script to prevent dns leak among other changes

**Comment by bubuntux** [comment] 2021-05-18 22:39
i believe this to be a duplicate of #165

**Closed by bubuntux** 2021-05-18 22:39 UTC
Labels: bug, help wanted
