### ISSUE TITLE
Issue with reverse proxy attached containers

### ISSUE THREAD

**Issue by animal6496** [bubuntux/nordvpn#61] opened 2020-02-27 03:19 UTC
Hi Julio,
Not a feature request more a question on usage. I'm using your image for a container to connect to NordVPN. Works as a charm! I've a connected Transmission container that I'd like to hide behind my nginx based reverse proxy. I've no clue how to achieve this. All my other containers play nicely together with nginx by adding them to my docker frontends bridge network and adding them to proxy.conf settings. I've tried to do this with the transmission container that didn't work (bad gateway).  I've also tried oxying to reverse proxy directly to the address and port of the transmission container, same result bad gateway. Is a reverse proxy setup possible at al and if how should I configure my docker network and/or nginx rev proxy settings?

**Comment by bubuntux** [comment] 2020-02-29 03:50
duplicate of #60 ?

**Comment by animal6496** [comment] 2020-02-29 17:08
Hi Julio,
Don't think so. As I read it in [#60](https://github.com/bubuntux/nordvpn/issues/60) the question was to add  proxy in the container. I don't wan to use this container as reverse proxy. I've already a fully configured nginx reverse proxy in a separate docker "frontends" network with ca. 15 frontend applications. I'd like to refer to the frontends (Transmission, SABnzbd, Hydra2) in the Nordvpn container network. My first idea was to add the external "frontends" network to the Nordvpn container in bridge mode. That didn't work (bad gateway). If I use a transmission container in the "frontends" network the reverse proxy works as expcted.
Also referring in the proxy.conf to domain.tld:9091 (transmission) doesn't work. Also this results in bad gateway. So my question is how does one refer in the reverse proxy to attached containers?
BTW if in the browser domain.tld:9091 does give me the transmission interface. Many thankx for having a look into this.

**Comment by bubuntux** [comment] 2020-03-19 15:30
I made this image to fulfill my needs, i'm gonna keep it public and you can use it at your own risk, if something doesn't work for you, sry but is up to you to fix it, unfortunately i don't have time to keep addressing ppls issues, from now on i'm only accepting pull requests.

**Comment by bubuntux** [comment] 2020-05-02 05:49
I added documentation (README) on how to use the web proxy

**Closed by bubuntux** 2020-05-02 05:49 UTC
Labels: help wanted, question
